const tracks=[
 {title:'Midnight City',artist:'M83',album:'Hurry Up, We’re Dreaming',genre:'Energy',duration:'4:03',cover:'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=300&q=80',src:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
 {title:'A Walk',artist:'Tycho',album:'Dive',genre:'Chill',duration:'5:21',cover:'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=300&q=80',src:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3'},
 {title:'Weightless',artist:'Marconi Union',album:'Ambient Works',genre:'Focus',duration:'4:48',cover:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=300&q=80',src:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3'},
 {title:'Sunset Lover',artist:'Petit Biscuit',album:'Presence',genre:'Chill',duration:'3:58',cover:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=300&q=80',src:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3'},
 {title:'The Less I Know',artist:'Tame Impala',album:'Currents',genre:'Energy',duration:'3:36',cover:'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=300&q=80',src:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3'}
];
let index=0, shuffled=false, repeat=false;
const audio=document.querySelector('#audio'), play=document.querySelector('#playBtn'), fill=document.querySelector('#progressFill'), list=document.querySelector('#trackList');
function render(filter='all'){list.innerHTML='';tracks.filter(t=>filter==='all'||t.genre===filter).forEach((t,i)=>{const real=tracks.indexOf(t);let row=document.createElement('div');row.className='track '+(real===index?'track-active':'');row.innerHTML=`<span class="track-num">${String(real+1).padStart(2,'0')}</span><img src="${t.cover}" alt=""><div class="track-main"><strong>${t.title}</strong><span>${t.artist} · ${t.genre}</span></div><span class="track-duration">${t.duration}</span><span>⋮</span>`;row.onclick=()=>{index=real;load(true)};list.appendChild(row)})}
function load(autoplay=false){let t=tracks[index];audio.src=t.src;document.querySelector('#cover').src=t.cover;document.querySelector('#title').textContent=t.title;document.querySelector('#artist').textContent=`${t.artist} · ${t.album}`;render(document.querySelector('.chip.active').dataset.filter);if(autoplay) audio.play().catch(()=>{});updateButton()}
function updateButton(){play.textContent=audio.paused?'▶':'Ⅱ';document.querySelector('#eq').classList.toggle('paused',audio.paused)}
play.onclick=()=>audio.paused?audio.play():audio.pause();audio.onplay=updateButton;audio.onpause=updateButton;audio.onended=()=>{if(repeat){audio.currentTime=0;audio.play()}else next()};audio.ontimeupdate=()=>{if(audio.duration){fill.style.width=`${audio.currentTime/audio.duration*100}%`;document.querySelector('#currentTime').textContent=fmt(audio.currentTime);document.querySelector('#duration').textContent=fmt(audio.duration)}};
function fmt(n){return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}function next(){index=shuffled?Math.floor(Math.random()*tracks.length):(index+1)%tracks.length;load(true)}function prev(){index=(index-1+tracks.length)%tracks.length;load(true)}document.querySelector('#nextBtn').onclick=next;document.querySelector('#prevBtn').onclick=prev;document.querySelector('#shuffleBtn').onclick=()=>{shuffled=!shuffled;document.querySelector('#shuffleBtn').style.color=shuffled?'var(--accent)':''};document.querySelector('#repeatBtn').onclick=()=>{repeat=!repeat;document.querySelector('#repeatBtn').style.color=repeat?'var(--accent)':''};document.querySelector('#queuePlay').onclick=()=>audio.paused?audio.play():audio.pause();document.querySelector('.progress').onclick=e=>{if(audio.duration)audio.currentTime=(e.offsetX/e.currentTarget.clientWidth)*audio.duration};document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');render(c.dataset.filter)});document.querySelector('#themeBtn').onclick=()=>document.body.classList.toggle('light');document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target===document.body){e.preventDefault();play.click()}if(e.code==='ArrowRight')next();if(e.code==='ArrowLeft')prev()});render();load();
